### ISSUE TITLE
Cannot delete entity when it is in a schema

### ISSUE THREAD

**Issue by andyneil** [outfielddigital/konstrukt#16]
**Describe the bug**
There is an error on the delete entity row action when the referenced entity is in a schema other than dbo.

**Steps To Reproduce**
1. Go to a collection
2. Click the actions menu and select "delete"
3. Confirm the delete in the modal

**Expected behavior**
The entity should be deleted

**Environment (please complete the following information):**
 - Server OS: Win10
 - Browser Chrome
 - Umbraco Version 9.5.0 (Also 9.4)
 - Product Version 1.1.0

```System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'SCHEMA.Table'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 281
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__31_0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery()
   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
   at NPoco.Database.Execute(Sql Sql)
   at Konstrukt.Persistence.DefaultKonstruktRepository.Delete(Object id, Boolean raiseEvents)```

**Comment by mattbrailsford** [comment]
Interesting. Maybe I need a ‘SetDbSchema’ option on the collection. 

Are you able to capture the actual SQL error message?

**Comment by mattbrailsford** [comment]
Actually, I think you might just need to express the schema in the table attribute of NPoco https://github.com/schotime/NPoco/issues/387#issuecomment-299038302

**Comment by andyneil** [comment]
It works fine for creating and updating, just deletes weirdly. I did try lots of variants but anything other than what I have errors on loading the collection to view so I figured this was correct:

```
[TableName("Finder.Clinician")]
[PrimaryKey("Id")]
public class Clinician
```

**Comment by mattbrailsford** [comment]
Ok. I’m away this week but will see what’s going on when I’m back Tuesday 👍🏻

**Comment by mattbrailsford** [comment]
@andyneil OK, there is a 1.1.1 beta build on our unstable feed if you want to test this. Looks like the delete statements was the only place we had a raw SQL statement and we weren't escaping the table name properly so I believe this is why it was failing. If you want to give the beta a try and let me know if it resolves your issue?

**Comment by andyneil** [comment]
Hi Matt - that sounds great. I can't see the 1.1.1 version on your feed though.

Also given that I've implemented "soft deletes" in the mean-time which mitigated the issues, it's made me wonder if it's possible to remove the normal delete button which would be useful in some circumstances?
I can see that you set visibility for custom actions but not sure that's available for the built in ones, maybe just the way I'm mis-reading the docs though. Happy to put in as a feature request if that's the case.

**Comment by mattbrailsford** [comment]
PS the beta will be on our unstable feed at https://nuget.outfield.digital/unstable/v3/index.json and you'll also need to ensure you allow the install of pre-releases

**Comment by andyneil** [comment]
Hi @mattbrailsford - that's super. I'd spotted the soft delete flag but given I'd implemented my own soft delete using a custom service, I still wanted to see the entities in another data view, allowing users to un-delete things. It actually forced me into writing a more robust solution for the customer.

I am using the unstable feed and it's not showing up for some reason.
![image](https://user-images.githubusercontent.com/12915243/168819952-868946a1-cdca-45a6-8c1c-1c9a53894f43.png)

Once it appears I'm happy to road-test it to then close the bug report.

**Comment by mattbrailsford** [comment]
Ooops, my bad, looks like it's building to the wrong version number. Let me fix it and I'll let you know :+1:

**Comment by mattbrailsford** [comment]
Ok, it should be there now :+1:

**Comment by andyneil** [comment]
Version 1.1.1-beta0060 resolves that issue. Deletes when table is in a schema now work wonderfully.
Thanks @mattbrailsford 👍

**Comment by andyneil** [comment]
No worries at all dude. I've worked round it for now using the custom
actions API, which is awesome by the way!
