### ISSUE TITLE
SqlDateTimeOverFlow when only one of the paired FilterableProperty for a DateTime is provided

### ISSUE THREAD

**Issue by matt-tolliday-iss** [outfielddigital/konstrukt#20]
**Describe the bug**
When using `.AddFilterableProperty(p => p.DateField)` on a DateTime field, and when using the filter only the first value is provided the following exception occurs:

![image](https://user-images.githubusercontent.com/80101704/169090816-0bcd06d9-fb8d-4fd0-906a-2f0d40538cca.png)

Nb: When two dates are provided, then the second value is removed, the entities are returned as expected. This only occurs when for the first "apply" of the filter only the first date of the pair is provided:

```
System.Data.SqlTypes.SqlTypeException: SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.
   at System.Data.SqlTypes.SqlDateTime.FromTimeSpan(TimeSpan value)
   at System.Data.SqlTypes.SqlDateTime.FromDateTime(DateTime value)
   at System.Data.SqlClient.MetaType.FromDateTime(DateTime dateTime, Byte cb)
   at System.Data.SqlClient.TdsParser.WriteUnterminatedValue(Object value, MetaType type, Byte scale, Int32 actualLength, Int32 encodingByteSize, Int32 offset, TdsParserStateObject stateObj, Int32 paramSize, Boolean isDataFeed)
   at System.Data.SqlClient.TdsParser.TDSExecuteRPCAddParameter(TdsParserStateObject stateObj, SqlParameter param, MetaType mt, Byte options)
   at System.Data.SqlClient.TdsParser.TdsExecuteRPC(_SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)
   at NPoco.Database.ExecuteScalar[T](String sql, CommandType commandType, Object[] args)
   at NPoco.Database.ExecuteScalar[T](Sql Sql)
   at NPoco.Database.ExecuteScalar[T](String sql, Object[] args)
   at NPoco.Database.PageImp[T,TRet](Int64 page, Int64 itemsPerPage, String sql, Object[] args, Func`3 executeQueryFunc)
   at NPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, String sql, Object[] args)
   at NPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, Sql sql)
```

**Steps To Reproduce**
1. Go to Filter tab of collection which includes a DateTime field property
2. Click on the first of the date pair filter inputs, and choose a date. Do not pick a "to" date value.
3. Apply filter

**Expected behavior**
The "from" date value should be used to filter the entity collection

**Environment (please complete the following information):**

- Server OS: Win10
- Browser Chrome
- Umbraco Version 9.5.0 (Also 9.4)
- Product Version 1.1.0 / 1.1.1-beta0060

**Additional context**
This does not occur in reverse, if only the "to" date pair value is supplied but no "from" value is selected.

**Comment by mattbrailsford** [comment]
Great detail. Ill add it to tomorrow’s todo list 👍🏻

**Comment by mattbrailsford** [comment]
This has now been resolved and will be available for testing on the unstable feed shortly (v1.1.1-betaXXXX)

**Comment by mattbrailsford** [comment]
v1.1.1 has now been released
