### ISSUE TITLE
Exception on opening dictionary items (or editing them) on Konstrukt 1.1.1

### ISSUE THREAD

**Issue by dampee** [outfielddigital/konstrukt#33]
**Describe the bug**
An exception is throw when trying to update dictionary items.
Due to a package dependency we are stuck on Umbraco v9 for now (and thus Konstrukt 1.1.1). Otherwise I would have upgraded first. 

**Steps To Reproduce**
Setup konstrukt as described in the documentation. 
If you add an AddContextAppAfter the dictionary items will not be updateable anymore. Note That the AddContextAppAfter has no special configuration to stop the dictionary items from working.

    .AddKonstrukt(cfg => { cfg.AddContextAppAfter("umbContent", "MyAppName", "icon-chat", ctx => {}) });

After adding (and running) the code above, a single click on a dictionary item in the backoffice. If we click a dictionary item to update them we get an exception (see below) thrown by the backoffice.

´´´ 
at Konstrukt.Web.Factories.KonstruktContextAppFactory.GetContentAppFor(Object source, IEnumerable`1 userGroups)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at Umbraco.Cms.Core.ContentApps.ContentAppFactoryCollection.GetContentAppsFor(Object o, IEnumerable`1 userGroups)
   at Umbraco.Cms.Core.Models.Mapping.CommonMapper.GetContentAppsForEntity(IEntity source)
   at Umbraco.Cms.Core.Models.Mapping.DictionaryMapDefinition.Map(IDictionaryItem source, DictionaryDisplay target, MapperContext context)
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, Type sourceType, MapperContext context)
   at Umbraco.Cms.Core.Mapping.UmbracoMapper.Map[TSource,TTarget](TSource source, MapperContext context)
   at Umbraco.Cms.Web.BackOffice.Controllers.DictionaryController.GetById(Int32 id)
   at lambda_method891(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
´´´ 

**Expected behavior**
An edit box to update the dictionary item, instead you get the as you get the exception: System.NullReferenceException, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Object reference not set to an instance of an object.

**Screenshots**

**Environment (please complete the following information):**
 - Server OS: Windows 10
 - Browser: all
 - Umbraco Version 9.5.2
 - Product Version: 1.1.1

**Additional context**

**Comment by dampee** [comment]
Updated with the exception

System.NullReferenceException, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Object reference not set to an instance of an object.

**Comment by dampee** [comment]
Here is the exception (after downloading the pdb)

![image](https://user-images.githubusercontent.com/1857460/179530976-cb014cb6-ab57-4018-9511-5d9919fb6596.png)

**Comment by mattbrailsford** [comment]
Ahhhh, I see. Hmm, I guess we could actually make that cast `IEntity` and not `IUmbracoEntity` as `HasIdentity` is defined on the `IEntity` interface and the DictionaryItem implements that interface.

I can implement this in our 1.4.1 hotfix branch, but it would require you to upgrade.

I do also need to see if dictionaries even support content apps, I didn't thing they really did 🤔

**Comment by dampee** [comment]
We do not need content app's in dictionaries (which is not supported I guess). It's another content app which tries to check if need to be added to that page I guess.

If change that line with a simple null check it works too, (I just tried with skipping that line in the debugger)

´´´
if(umbracoIdentity == null || !umbracoEntity.HasIdentity)  {
´´´

We cannot yet upgrade due to another community package stopping us from upgrading to v10. If you could make a v1.1.2 patch, that would be awesome (for people stuck on v9 for now). I'll see if we can work around the limitation from the other package.

**Comment by mattbrailsford** [comment]
I've created a support build for you wich you can access here https://www.dropbox.com/s/8x5z3rf5jxserje/Konstrukt.1.1.2-support0002.zip?dl=0 where the entity has been null checked. You'll need to extract the zip and then use the folder as a local NuGet source, but it should just install over the top.

**Comment by dampee** [comment]
For those having the same issue: the above build fixes the issue.
Extract the folder in your solution, and then add a file in your root called nuget.config. Enable prerelease and upgrade the konstruct package.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<packageSources>
		<clear />
		<!-- `key` can be any identifier for your source. -->
		<add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
		<add key="Konstrukt" value="Konstrukt.1.1.2-support0002" />
	</packageSources>
</configuration>
```

**Comment by mattbrailsford** [comment]
Just to be clear, that is only necesarry for your situation where you can't upgrade past 1.1.1. Everyone else should just use 1.5.0 where this fix is already merged in.
